title: This Final Project # your name (or website title) here
logo: "/images/eric-englin.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Using Reddit and Twitter posts to predict election outcomes.
  <br><br>
  <b>Main Links</b>
  
  <a href="https://nlp-election-predictions.github.io/elections/">Home Page</a>
  <br>
  <a href="https://nlp-election-predictions.github.io/elections/pages/reddit-data-pull.html">Reddit Data Pull</a>
  <br>
  <a href="https://nlp-election-predictions.github.io/elections/pages/reddit-eda.html">Reddit EDA</a>
  <br>
  <a href="https://nlp-election-predictions.github.io/elections/pages/nlp-model-dev.html">NLP Model Development</a>
  <br>
  <a href="https://nlp-election-predictions.github.io/elections/pages/models-trained.html">Models Trained</a>
  <br>
  <a href="https://nlp-election-predictions.github.io/elections/pages/results.html">Final Results & Conclusion</a>
  <br>
  <br>
  <br>
  <b>Other Links</b>

  <a href="https://nlp-election-predictions.github.io/elections/pages/other-api.html">Other APIs Considered</a>
  <br>
  <a href="https://nlp-election-predictions.github.io/elections/pages/about-us.html">About Us</a>
  <br>
  <a href="https://github.com/NLP-Election-Predictions/elections">Github Repo (Website)</a>
  <br>
  <a href="https://github.com/jschneids13/CS109a-Group-81-Final-Project">Github Repo (Code)</a>

theme: jekyll-theme-tactile

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: true
