title: This Final Project # your name (or website title) here
logo: "/images/eric-englin.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Using Reddit and Twitter posts to predict election outcomes.
  <br><br>
  <a href="https://github.com/NLP-Election-Predictions/elections">Github Repo</a>
  <br>
  <a href="https://nlp-election-predictions.github.io/elections/pages/about-us.html">Github Repo</a>

theme: jekyll-theme-tactile

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: true
